diff --git a/src/testlib/qtestresult.cpp b/src/testlib/qtestresult.cpp
index 79ea22b..14ab29a 100644
--- a/src/testlib/qtestresult.cpp
+++ b/src/testlib/qtestresult.cpp
@@ -237,7 +237,10 @@ bool QTestResult::verify(bool statement, const char *statementStr,
         QTestLog::info(msg, file, line);
     }
 
-    qsnprintf(msg, 1024, "'%s' returned FALSE. (%s)", statementStr, description);
+    const char * format = QTest::expectFailMode
+        ? "'%s' returned TRUE unexpectedly. (%s)"
+        : "'%s' returned FALSE. (%s)";
+    qsnprintf(msg, 1024, format, statementStr, description);
 
     return checkStatement(statement, msg, file, line);
 }
diff --git a/tests/auto/testlib/selftests/expected_expectfail.lightxml b/tests/auto/testlib/selftests/expected_expectfail.lightxml
index 8fdac12..c808886 100644
--- a/tests/auto/testlib/selftests/expected_expectfail.lightxml
+++ b/tests/auto/testlib/selftests/expected_expectfail.lightxml
@@ -95,13 +95,13 @@
 </TestFunction>
 <TestFunction name="xpass">
 <Incident type="xpass" file="/home/user/dev/qt5/qtbase/tests/auto/testlib/selftests/expectfail/tst_expectfail.cpp" line="190">
-    <Description><![CDATA['true' returned FALSE. ()]]></Description>
+    <Description><![CDATA['true' returned TRUE unexpectedly. ()]]></Description>
 </Incident>
 </TestFunction>
 <TestFunction name="xpassDataDriven">
 <Incident type="xpass" file="/home/user/dev/qt5/qtbase/tests/auto/testlib/selftests/expectfail/tst_expectfail.cpp" line="212">
     <DataTag><![CDATA[XPass]]></DataTag>
-    <Description><![CDATA['true' returned FALSE. ()]]></Description>
+    <Description><![CDATA['true' returned TRUE unexpectedly. ()]]></Description>
 </Incident>
 <Incident type="pass" file="" line="0">
     <DataTag><![CDATA[Pass]]></DataTag>
diff --git a/tests/auto/testlib/selftests/expected_expectfail.txt b/tests/auto/testlib/selftests/expected_expectfail.txt
index f1ad406..b11ff05 100644
--- a/tests/auto/testlib/selftests/expected_expectfail.txt
+++ b/tests/auto/testlib/selftests/expected_expectfail.txt
@@ -34,9 +34,9 @@ XFAIL  : tst_ExpectFail::xfailOnAnyRow(second row) This test should xfail
 PASS   : tst_ExpectFail::xfailOnAnyRow(second row)
 FAIL!  : tst_ExpectFail::xfailWithoutVerify(first row) QEXPECT_FAIL was called without any subsequent verification statements
 FAIL!  : tst_ExpectFail::xfailWithoutVerify(second row) QEXPECT_FAIL was called without any subsequent verification statements
-XPASS  : tst_ExpectFail::xpass() 'true' returned FALSE. ()
+XPASS  : tst_ExpectFail::xpass() 'true' returned TRUE unexpectedly. ()
    Loc: [/home/user/dev/qt5/qtbase/tests/auto/testlib/selftests/expectfail/tst_expectfail.cpp(190)]
-XPASS  : tst_ExpectFail::xpassDataDriven(XPass) 'true' returned FALSE. ()
+XPASS  : tst_ExpectFail::xpassDataDriven(XPass) 'true' returned TRUE unexpectedly. ()
    Loc: [/home/user/dev/qt5/qtbase/tests/auto/testlib/selftests/expectfail/tst_expectfail.cpp(212)]
 PASS   : tst_ExpectFail::xpassDataDriven(Pass)
 PASS   : tst_ExpectFail::cleanupTestCase()
diff --git a/tests/auto/testlib/selftests/expected_expectfail.xml b/tests/auto/testlib/selftests/expected_expectfail.xml
index cb061f5..229b0ae 100644
--- a/tests/auto/testlib/selftests/expected_expectfail.xml
+++ b/tests/auto/testlib/selftests/expected_expectfail.xml
@@ -97,13 +97,13 @@
 </TestFunction>
 <TestFunction name="xpass">
 <Incident type="xpass" file="/home/user/dev/qt5/qtbase/tests/auto/testlib/selftests/expectfail/tst_expectfail.cpp" line="190">
-    <Description><![CDATA['true' returned FALSE. ()]]></Description>
+    <Description><![CDATA['true' returned TRUE unexpectedly. ()]]></Description>
 </Incident>
 </TestFunction>
 <TestFunction name="xpassDataDriven">
 <Incident type="xpass" file="/home/user/dev/qt5/qtbase/tests/auto/testlib/selftests/expectfail/tst_expectfail.cpp" line="212">
     <DataTag><![CDATA[XPass]]></DataTag>
-    <Description><![CDATA['true' returned FALSE. ()]]></Description>
+    <Description><![CDATA['true' returned TRUE unexpectedly. ()]]></Description>
 </Incident>
 <Incident type="pass" file="" line="0">
     <DataTag><![CDATA[Pass]]></DataTag>
diff --git a/tests/auto/testlib/selftests/expected_expectfail.xunitxml b/tests/auto/testlib/selftests/expected_expectfail.xunitxml
index d13cf66..ca13559 100644
--- a/tests/auto/testlib/selftests/expected_expectfail.xunitxml
+++ b/tests/auto/testlib/selftests/expected_expectfail.xunitxml
@@ -35,10 +35,10 @@
     <failure tag="second row" message="QEXPECT_FAIL was called without any subsequent verification statements" result="fail"/>
   </testcase>
   <testcase result="xpass" name="xpass">
-    <failure message="&apos;true&apos; returned FALSE. ()" result="xpass"/>
+    <failure message="&apos;true&apos; returned TRUE unexpectedly. ()" result="xpass"/>
   </testcase>
   <testcase result="xpass" name="xpassDataDriven">
-    <failure tag="XPass" message="&apos;true&apos; returned FALSE. ()" result="xpass"/>
+    <failure tag="XPass" message="&apos;true&apos; returned TRUE unexpectedly. ()" result="xpass"/>
   </testcase>
   <testcase result="pass" name="cleanupTestCase"/>
   <system-err>
diff --git a/tests/auto/testlib/selftests/expected_xunit.lightxml b/tests/auto/testlib/selftests/expected_xunit.lightxml
index 35108fc..71a5737 100644
--- a/tests/auto/testlib/selftests/expected_xunit.lightxml
+++ b/tests/auto/testlib/selftests/expected_xunit.lightxml
@@ -45,7 +45,7 @@
 </TestFunction>
 <TestFunction name="testFunc7">
 <Incident type="xpass" file="/home/user/dev/qt5/qtbase/tests/auto/testlib/selftests/xunit/tst_xunit.cpp" line="110">
-    <Description><![CDATA['true' returned FALSE. ()]]></Description>
+    <Description><![CDATA['true' returned TRUE unexpectedly. ()]]></Description>
 </Incident>
 </TestFunction>
 <TestFunction name="cleanupTestCase">
diff --git a/tests/auto/testlib/selftests/expected_xunit.txt b/tests/auto/testlib/selftests/expected_xunit.txt
index ae2508c..51c8f89 100644
--- a/tests/auto/testlib/selftests/expected_xunit.txt
+++ b/tests/auto/testlib/selftests/expected_xunit.txt
@@ -19,7 +19,7 @@ PASS   : tst_Xunit::testFunc5()
 XFAIL  : tst_Xunit::testFunc6() this failure is also expected
    Loc: [/home/user/dev/qt5/qtbase/tests/auto/testlib/selftests/xunit/tst_xunit.cpp(104)]
 PASS   : tst_Xunit::testFunc6()
-XPASS  : tst_Xunit::testFunc7() 'true' returned FALSE. ()
+XPASS  : tst_Xunit::testFunc7() 'true' returned TRUE unexpectedly. ()
    Loc: [/home/user/dev/qt5/qtbase/tests/auto/testlib/selftests/xunit/tst_xunit.cpp(110)]
 PASS   : tst_Xunit::cleanupTestCase()
 Totals: 5 passed, 3 failed, 1 skipped
diff --git a/tests/auto/testlib/selftests/expected_xunit.xml b/tests/auto/testlib/selftests/expected_xunit.xml
index 0fe9735..a1e6b20 100644
--- a/tests/auto/testlib/selftests/expected_xunit.xml
+++ b/tests/auto/testlib/selftests/expected_xunit.xml
@@ -47,7 +47,7 @@
 </TestFunction>
 <TestFunction name="testFunc7">
 <Incident type="xpass" file="/home/user/dev/qt5/qtbase/tests/auto/testlib/selftests/xunit/tst_xunit.cpp" line="110">
-    <Description><![CDATA['true' returned FALSE. ()]]></Description>
+    <Description><![CDATA['true' returned TRUE unexpectedly. ()]]></Description>
 </Incident>
 </TestFunction>
 <TestFunction name="cleanupTestCase">
diff --git a/tests/auto/testlib/selftests/expected_xunit.xunitxml b/tests/auto/testlib/selftests/expected_xunit.xunitxml
index e77004f..e740344 100644
--- a/tests/auto/testlib/selftests/expected_xunit.xunitxml
+++ b/tests/auto/testlib/selftests/expected_xunit.xunitxml
@@ -27,7 +27,7 @@
     <!-- message="this failure is also expected" type="info" -->
   </testcase>
   <testcase result="xpass" name="testFunc7">
-    <failure message="&apos;true&apos; returned FALSE. ()" result="xpass"/>
+    <failure message="&apos;true&apos; returned TRUE unexpectedly. ()" result="xpass"/>
   </testcase>
   <testcase result="pass" name="cleanupTestCase"/>
   <system-err>